on:
  workflow_dispatch:
  schedule:
    - cron: '47 * * * *'

jobs:
  tests-transcript:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        base-version:
          - 'releases/latest'
          - 'main'
        ucm-release-version:
          - 'release%2F0.5.23'
          - 'release%2F0.5.27'
          - 'trunk-build'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run tests transcript
        env:
          UNISON_BASE_VERSION: ${{ matrix.base-version }}
          UCM_RELEASE: ${{ matrix.ucm-release-version }}
          UNISON_DEBUG: timing
        run: |
          apt-get update && apt-get -y install gettext-base
          cd tests
          ./run-tests.sh
